// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7xCMnX_5xVyRcuHhbJqD1ZvTGQX1hdk',
    appId: '1:368090559485:web:a523c17e802c7a8d76df94',
    messagingSenderId: '368090559485',
    projectId: 'applicationdev2-63076',
    authDomain: 'applicationdev2-63076.firebaseapp.com',
    databaseURL: 'https://applicationdev2-63076-default-rtdb.firebaseio.com',
    storageBucket: 'applicationdev2-63076.firebasestorage.app',
    measurementId: 'G-63QWHCDGF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-Bah8o8UjgG0g0UOVXts3Gg8fxXDHdY',
    appId: '1:368090559485:android:c4ba976ca032f5a076df94',
    messagingSenderId: '368090559485',
    projectId: 'applicationdev2-63076',
    databaseURL: 'https://applicationdev2-63076-default-rtdb.firebaseio.com',
    storageBucket: 'applicationdev2-63076.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs7xCMnX_5xVyRcuHhbJqD1ZvTGQX1hdk',
    appId: '1:368090559485:web:0fad96fd1c066d9376df94',
    messagingSenderId: '368090559485',
    projectId: 'applicationdev2-63076',
    authDomain: 'applicationdev2-63076.firebaseapp.com',
    databaseURL: 'https://applicationdev2-63076-default-rtdb.firebaseio.com',
    storageBucket: 'applicationdev2-63076.firebasestorage.app',
    measurementId: 'G-ZKECXG75EE',
  );
}
